repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: jetstack
    url: https://charts.jetstack.io
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: stable
    url: https://charts.helm.sh/stable
