---
helmDefaults:
  atomic: false
  force: false
  timeout: 600
  wait: true

repositories:
  - name: captain-hook
    url: https://jenkins-infra.github.io/captain-hook

releases:
  - name: captain-hook
    chart: captain-hook/captain-hook
    version: 0.0.17
    namespace: jenkins-infra
    values:
      - "../config/default/captain-hook.yaml"
    set:
      - name: namespace
        value: jenkins-infra
