repositories:
  - name: datadog
    url: https://helm.datadoghq.com
releases:
  - name: datadog
    namespace: datadog
    chart: datadog/datadog
    version: 2.9.0
    wait: true
    timeout: 300
    atomic: true
    values:
      - "../config/default/datadog.yaml"
    secrets:
      - "../secrets/config/datadog/secrets.yaml"
