repositories:
  - name: stable
    url: https://charts.helm.sh/stable
releases:
    - name: private-dex
      chart: stable/dex
      namespace: dex
      wait: true
      timeout: 300
      force: false
      atomic: true
      values:
        - "../config/default/dex.yaml"
      secrets:
        - "../secrets/config/dex/secrets.yaml"
