repositories:
  - name: falco
    url: https://falcosecurity.github.io/charts
releases:
  - name: falco
    namespace: falco
    chart: falco/falco
    version: 1.11.0
    wait: true
    timeout: 100
    atomic: true
    values:
      - "../config/default/falco.yaml"
